server.port=8080

aws.region=${AWS_REGION}
aws.accessKeyId=${AWS_ACCESS_KEY_ID}
aws.secretKey=${AWS_SECRET_ACCESS_KEY}
aws.dynamodb.tableName=ir_cracks_detection

aws.iot.broker.url=${AWS_IOT_BROKER_URL}
aws.iot.broker.clientId=springboot-backend-001
aws.iot.topic.filter=device/#
aws.iot.keystore.path=mqtt-keystore.p12
aws.iot.keystore.password=${AWS_IOT_KEYSTORE_PASSWORD}